"""Commercial-grade offline worker boundary for MediaTranscribeStudio."""

from .adapters import (
    AdapterContext,
    JavaPdfRendererAdapter,
    ReportRendererAdapter,
    TranscriptionAdapter,
    UnavailableRendererAdapter,
    UnavailableTranscriptionAdapter,
)
from .errors import JobCancelled, WorkerError
from .business_processing import (
    BUSINESS_PROMPT_VERSION,
    BUSINESS_SCHEMA_VERSION,
    BusinessProcessingConfig,
    BusinessProcessingRunner,
)
from .local_llm import (
    LocalLLMConfig,
    LocalLLMError,
    LocalLLMProvider,
    MappingLocalLLMProvider,
    OllamaLocalProvider,
)
from .models import (
    CHECKPOINT_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    TRANSCRIPT_SCHEMA_VERSION,
    JobStatus,
    RenderArtifact,
    RenderResult,
    SpeakerCountEstimate,
    SpeakerCountMode,
    SpeakerCountPolicy,
    StartJobRequest,
    TranscriptSegment,
    TranscriptionResult,
    canonical_speaker_ids,
    validate_job_id,
)
from .paths import PathPolicy
from .protocol import JsonlEmitter, WorkerProtocol, run_jsonl_loop
from .composition import (
    ProductionComposition,
    ProductionFactories,
    build_production_composition,
)
from .production_config import (
    PRODUCTION_CONFIG_SCHEMA_VERSION,
    PRODUCTION_MODE,
    PreflightCheck,
    ProductionConfig,
    ProductionConfigError,
    ProductionExecutables,
    ProductionModels,
    ProductionPaths,
    ProductionPdfPolicy,
    ProductionPreflightReport,
    ProductionRuntime,
    ProductionSpeakerPolicy,
    apply_offline_environment,
    offline_environment,
    production_diagnostics,
    run_production_preflight,
)
from .production_runners import (
    FfmpegFunAsrPreparationAdapter,
    LocalERes2NetV2Verifier,
    LocalFunAsrCamPlusAdapter,
    LocalPyannoteAuditAdapter,
    LocalQwen3AsrAdapter,
)
from .service import WorkerService

__all__ = [
    "AdapterContext",
    "BUSINESS_PROMPT_VERSION",
    "BUSINESS_SCHEMA_VERSION",
    "BusinessProcessingConfig",
    "BusinessProcessingRunner",
    "CHECKPOINT_SCHEMA_VERSION",
    "JobCancelled",
    "JobStatus",
    "JsonlEmitter",
    "LocalLLMConfig",
    "LocalLLMError",
    "LocalLLMProvider",
    "MappingLocalLLMProvider",
    "JavaPdfRendererAdapter",
    "FfmpegFunAsrPreparationAdapter",
    "LocalERes2NetV2Verifier",
    "LocalFunAsrCamPlusAdapter",
    "LocalPyannoteAuditAdapter",
    "LocalQwen3AsrAdapter",
    "PROTOCOL_VERSION",
    "PRODUCTION_CONFIG_SCHEMA_VERSION",
    "PRODUCTION_MODE",
    "PathPolicy",
    "PreflightCheck",
    "ProductionComposition",
    "ProductionConfig",
    "ProductionConfigError",
    "ProductionExecutables",
    "ProductionFactories",
    "ProductionModels",
    "ProductionPaths",
    "ProductionPdfPolicy",
    "ProductionPreflightReport",
    "ProductionRuntime",
    "ProductionSpeakerPolicy",
    "RenderArtifact",
    "RenderResult",
    "ReportRendererAdapter",
    "SpeakerCountEstimate",
    "SpeakerCountMode",
    "SpeakerCountPolicy",
    "StartJobRequest",
    "TRANSCRIPT_SCHEMA_VERSION",
    "TranscriptSegment",
    "TranscriptionAdapter",
    "TranscriptionResult",
    "UnavailableRendererAdapter",
    "UnavailableTranscriptionAdapter",
    "OllamaLocalProvider",
    "WorkerError",
    "WorkerProtocol",
    "WorkerService",
    "apply_offline_environment",
    "build_production_composition",
    "canonical_speaker_ids",
    "offline_environment",
    "production_diagnostics",
    "run_jsonl_loop",
    "run_production_preflight",
    "validate_job_id",
]
